server:
  port: 8082
spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

users-service:
  url: ${USER_SERVICE_URL}
